--Spell Vendor listing by location, class, and level if applicable--
local MerchLookup = {
    poknowledge = {
        WAR = { ["Heldin Swordbreaker"] = { vendormin = 1, vendormax = 90, }, },
        PAL = {
            ["Cavalier Waut"] = { vendormin = 1, vendormax = 70, },
            ["Cavalier Aodus"] = { vendormin = 26, vendormax = 70, },
            ["Cavalier Preradus"] = { vendormin = 51, vendormax = 70, },
            ["Cavalier Cerakor"] = { vendormin = 61, vendormax = 70, },
            ["Cavalier Ethigom"] = { vendormin = 71, vendormax = 70, },
            ["Cavalier Tummings"] = { vendormin = 81, vendormax = 70, },
            ["Ulin Velnik"] = { vendormin = 51, vendormax = 70, },
        },
        SHD = {
            ["Reaver Nydlil"] = { vendormin = 1, vendormax = 70, },
            ["Reaver Uledrith"] = { vendormin = 1, vendormax = 70, },
            ["Reaver Thirlan"] = { vendormin = 1, vendormax = 70, },
            ["Reaver Muron"] = { vendormin = 1, vendormax = 70, },
            ["Reaver Praden"] = { vendormin = 1, vendormax = 70, },
            --["Reaver Enold"] = { vendormin = 1, vendormax = 90, },
            ["Zhao V`karin"] = { vendormin = 1, vendormax = 90, },
        },
        BST = {
            ["Primalist Saosith"] = { vendormin = 1, vendormax = 70, },
            ["Primalist Worenon"] = { vendormin = 1, vendormax = 70, },
            ["Primalist Nydalith"] = { vendormin = 1, vendormax = 70, },
            ["Primalist Loerith"] = { vendormin = 1, vendormax = 70, },
            ["Primalist Uliag"] = { vendormin = 1, vendormax = 70, },
            ["Primalist Beal"] = { vendormin = 1, vendormax = 70, },
            ["Tana Clawguard"] = { vendormin = 1, vendormax = 70, },
        },
        BER = {
            ["Gaddi Buruca"] = { vendormin = 1, vendormax = 90, },
            ["Kurlond Axebringer"] = { vendormin = 1, vendormax = 90, },
        },
        MNK = { ["Beorobin Amondson"] = { vendormin = 1, vendormax = 90, }, },
        RNG = {
            ["Pathfinder Viliken"] = { vendormin = 1, vendormax = 70, },
            ["Pathfinder Vaered"] = { vendormin = 1, vendormax = 70, },
            ["Pathfinder Thoajin"] = { vendormin = 1, vendormax = 70, },
            ["Pathfinder Naend"] = { vendormin = 1, vendormax = 70, },
            ["Pathfinder Arelat"] = { vendormin = 1, vendormax = 70, },
            ["Pathfinder Sweeneph"] = { vendormin = 1, vendormax = 70, },
            ["Keshyk Wardorn"] = { vendormin = 1, vendormax = 70, },
        },
        ROG = { ["Blane Darkblade"] = { vendormin = 1, vendormax = 90, }, },
        MAG = {
            ["Elementalist Somat"] = { vendormin = 1, vendormax = 70, },
            ["Elementalist Kaeob"] = { vendormin = 1, vendormax = 70, },
            ["Elementalist Padan"] = { vendormin = 1, vendormax = 70, },
            ["Elementalist Siewth"] = { vendormin = 1, vendormax = 70, },
            ["Elementalist Onaec"] = { vendormin = 1, vendormax = 80, },
            -- ["Elementalist Bartbur"] = { vendormin = 1, vendormax = 90, },
        },
        NEC = {
            ["Heretic Drahur"] = { vendormin = 1, vendormax = 70, },
            ["Heretic Elirev"] = { vendormin = 1, vendormax = 70, },
            ["Heretic Edalith"] = { vendormin = 1, vendormax = 70, },
            ["Heretic Ceikon"] = { vendormin = 1, vendormax = 70, },
            ["Heretic Niraf"] = { vendormin = 1, vendormax = 70, },
            -- ["Heretic Lartman"] = { vendormin = 1, vendormax = 70, },
        },
        WIZ = {
            ["Channeler Olaemos"] = { vendormin = 1, vendormax = 70, },
            ["Channeler Lariland"] = { vendormin = 1, vendormax = 70, },
            ["Channeler Cerakoth"] = { vendormin = 1, vendormax = 70, },
            ["Channeler Alyrianne"] = { vendormin = 1, vendormax = 70, },
            ["Channeler Keatrem"] = { vendormin = 1, vendormax = 70, },
            -- ["Channeler Larkord"] = { vendormin = 1, vendormax = 70, },
        },
        BRD = {
            ["Minstrel Eoweril"] = { vendormin = 1, vendormax = 70, },
            ["Minstrel Joet"] = { vendormin = 1, vendormax = 70, },
            ["Minstrel Gwiar"] = { vendormin = 1, vendormax = 70, },
            ["Minstrel Silnon"] = { vendormin = 1, vendormax = 70, },
            ["Minstrel Cirsaelle"] = { vendormin = 1, vendormax = 70, },
            ["Minstrel Franchot"] = { vendormin = 1, vendormax = 70, },
            -- ["Larquin Julinok"] = { vendormin = 1, vendormax = 70, },
        },
        ENC = {
            ["Illusionist Jerup"] = { vendormin = 1, vendormax = 70, },
            ["Illusionist Sevat"] = { vendormin = 1, vendormax = 70, },
            ["Illusionist Lobaen"] = { vendormin = 1, vendormax = 70, },
            ["Illusionist Acored"] = { vendormin = 1, vendormax = 70, },
            ["Illusionist Warek"] = { vendormin = 1, vendormax = 70, },
            -- ["Illusionist Phili"] = { vendormin = 1, vendormax = 90, },
        },
        CLR = {
            ["Vicar Ceraen"] = { vendormin = 1, vendormax = 70, },
            ["Vicar Thiran"] = { vendormin = 1, vendormax = 70, },
            ["Vicar Delin"] = { vendormin = 1, vendormax = 70, },
            ["Vicar Diarin"] = { vendormin = 1, vendormax = 70, },
            ["Vicar Glaunn"] = { vendormin = 1, vendormax = 70, },
            -- ["Vicar Feyl"] = { vendormin = 1, vendormax = 90, },
        },
        DRU = {
            ["Wanderer Astobin"] = { vendormin = 1, vendormax = 70, },
            ["Wanderer Qenda"] = { vendormin = 1, vendormax = 70, },
            ["Wanderer Frardok"] = { vendormin = 1, vendormax = 70, },
            ["Wanderer Kedrisan"] = { vendormin = 1, vendormax = 70, },
            ["Wanderer Thermon"] = { vendormin = 1, vendormax = 70, },
            --["Wanderer Abel"] = { vendormin = 1, vendormax = 70, },
        },
        SHM = {
            ["Mystic Abomin"] = { vendormin = 1, vendormax = 70, },
            ["Mystic Goharkor"] = { vendormin = 1, vendormax = 70, },
            ["Mystic Ryrin"] = { vendormin = 1, vendormax = 70, },
            ["Mystic Pikor"] = { vendormin = 1, vendormax = 70, },
            ["Mystic Somas"] = { vendormin = 1, vendormax = 70, },
            --["Mystic Voskovek"] = { vendormin = 1, vendormax = 70, },
        },
    },
    abysmal = {
        WAR = { "Godain MacKodor", 'Vuldoleky Koranin', },
        PAL = { "Godain MacKodor", 'Slewar Belsgog', 'Romida Truesword', },
        SHD = { "Godain MacKodor", 'Daris Rodril', 'Romida Truesword', },
        BST = { "Godain MacKodor", "Adnia Pashdi", 'Romida Truesword', },
        BER = { "Godain MacKodor", 'Shuris MacLurin', 'Saylsa Growlur', 'Romida Truesword', },
        MNK = { "Godain MacKodor", 'Merktal Skriek', },
        RNG = { "Godain MacKodor", 'Dadein Shadowbow', 'Romida Truesword', },
        ROG = { "Godain MacKodor", 'Romida Truesword', 'Glane Brixgot', },
        MAG = { "Godain MacKodor", 'Ardtia Aughsan', },
        NEC = { "Godain MacKodor", 'Yiem Rynawu', },
        WIZ = { "Verna Leinar", "Godain MacKodor", 'Gruppip Fooedli', },
        BRD = { "Godain MacKodor", 'Ylian Darsdi', 'Romida Truesword', },
        ENC = { "Godain MacKodor", 'Phoenth Ingven', },
        CLR = { "Godain MacKodor", 'Sosina Mardar', },
        DRU = { "Verna Leinar", 'Godain MacKodor', 'Burumy Fahon', },
        SHM = { "Hatem", "Godain MacKodor", },
    },
    argath = {
        WAR = { 'Danibi', },
        PAL = { 'Ephinia', 'Danibi', },
        SHD = { 'Shelif', 'Danibi', 'Prilt', 'Ephinia', },
        BST = { 'Stup', 'Danibi', 'Prilt', 'Matima', },
        BER = { 'Danibi', },
        MNK = { 'Danibi', },
        RNG = { 'Danibi', "Wonav", },
        ROG = { 'Danibi', },
        MAG = { "Matima", "Prilt", "Wonav", "Stup", },
        NEC = { "Shelif", "Prilt", "Matima", },
        WIZ = { "Matima", "Prilt", },
        BRD = { "Nori", "Prilt", "Danibi", },
        ENC = { "Nori", "Prilt", "Matima", },
        CLR = { "Ephinia", "Prilt", },
        DRU = { "Wonav", "Prilt", "Ephinia", "Stup", },
        SHM = { "Prilt", "Stup", "Wonav", },
    },
    shardslanding = {
        WAR = { "Went", },
        PAL = { "Olivia", "Went", },
        SHD = { "Lirit", "Went", },
        BST = { "Varille", "Went", },
        BER = { "Went", },
        MNK = { "Went", },
        RNG = { "Went", "Noel", },
        ROG = { "Went", },
        MAG = { "Gilab", },
        NEC = { "Lirit", },
        WIZ = { "Gilab", },
        BRD = { "Gilbert", "Went", },
        ENC = { "Gilbert", },
        CLR = { "Olivia", },
        DRU = { "Noel", },
        SHM = { "Varille", },
    },
    ethernere = {
        WAR = { "Jupitus", },
        PAL = { "Danelia", },
        SHD = { "Julaea", },
        BST = { "Jarkan", },
        BER = { "Sund", },
        MNK = { "Jupitus", },
        RNG = { "Roth", },
        ROG = { "Julaea", },
        MAG = { "Saera", },
        NEC = { "Sevanta", },
        WIZ = { "Saera", 'Jimmar', },
        BRD = { "Allan", },
        ENC = { "Saera", },
        CLR = { "Danelia", },
        DRU = { "Well", 'Roth', },
        SHM = { "Temvin", },
    },
    kattacastrumb = {
        WAR = { "Bellona", },
        PAL = { "Valerian", 'Bellona', },
        SHD = { "Angeronia", 'Bellona', },
        BST = { "Psyche", 'Bellona', },
        BER = { "Bellona", },
        MNK = { "Bellona", },
        RNG = { "Philyra", 'Bellona', },
        ROG = { "Bellona", },
        MAG = { "Canicus", },
        NEC = { "Angeronia", },
        WIZ = { "Canicus", 'Adrastea', },
        BRD = { "Galenus", 'Bellona', },
        ENC = { "Galenus", },
        CLR = { "Valerian", },
        DRU = { "Philyra", },
        SHM = { "Psyche", },
    },
    potranquility = {
        WAR = { "Warlowe Rida", },
        PAL = { "Warlowe Rida", },
        SHD = { "Warlowe Rida", },
        BST = { "Warlowe Rida", },
        BER = { "Warlowe Rida", },
        MNK = { "Warlowe Rida", },
        RNG = { "Warlowe Rida", },
        ROG = { "Warlowe Rida", },
        MAG = { "Warlowe Rida", },
        NEC = { "Warlowe Rida", },
        WIZ = { "Warlowe Rida", },
        BRD = { "Warlowe Rida", },
        ENC = { "Warlowe Rida", },
        CLR = { "Warlowe Rida", },
        DRU = { "Warlowe Rida", },
        SHM = { "Warlowe Rida", },
    },
    lceanium = {
        WAR = { "Janeil", },
        PAL = { "Janeil", },
        SHD = { "Janeil", },
        BST = { "Janeil", },
        BER = { "Janeil", },
        MNK = { "Janeil", },
        RNG = { "Janeil", },
        ROG = { "Janeil", },
        MAG = { "Janeil", },
        NEC = { "Janeil", },
        WIZ = { "Janeil", },
        BRD = { "Janeil", },
        ENC = { "Janeil", },
        CLR = { "Janeil", },
        DRU = { "Janeil", },
        SHM = { "Janeil", },
    },
    overtheretwo = {
        WAR = { "Cromslor", },
        PAL = { "Frinshalor", 'Cromslor', },
        SHD = { "Druwdav", },
        BST = { "Pinskidan", 'Cromslor', },
        BER = { "Cromslor", },
        MNK = { "Cromslor", },
        RNG = { "Zowikinski", 'Cromslor', },
        ROG = { "Cromslor", },
        MAG = { "Kris", },
        NEC = { "Druwdav", },
        WIZ = { "Kris", },
        BRD = { "Irarae", 'Cromslor', },
        ENC = { "Irarae", },
        CLR = { "Frinshalor", },
        DRU = { "Zowikinski", },
        SHM = { "Pinskidan", },
    },
    stratos = {
        WAR = { "Fairelwil", 'Virtuous Dusk', },
        PAL = { "Fairelwil", 'Virtuous Dusk', },
        SHD = { "Fairelwil", 'Virtuous Dusk', },
        BST = { "Fairelwil", 'Virtuous Dusk', },
        BER = { "Fairelwil", 'Virtuous Dusk', },
        MNK = { "Fairelwil", 'Virtuous Dusk', },
        RNG = { "Fairelwil", 'Virtuous Dusk', },
        ROG = { "Fairelwil", 'Virtuous Dusk', },
        MAG = { "Fairelwil", 'Virtuous Dusk', },
        NEC = { "Fairelwil", 'Virtuous Dusk', },
        WIZ = { "Fairelwil", 'Virtuous Dusk', },
        BRD = { "Fairelwil", 'Virtuous Dusk', },
        ENC = { "Fairelwil", 'Virtuous Dusk', },
        CLR = { "Fairelwil", 'Virtuous Dusk', },
        DRU = { "Fairelwil", 'Virtuous Dusk', },
        SHM = { "Fairelwil", 'Virtuous Dusk', },
    },
    eastwastestwo = {
        WAR = { "Yluc Culmin", },
        PAL = { "Yluc Culmin", 'Maulemas Ragejoy', },
        SHD = { "Yluc Culmin", 'Maulemas Ragejoy', 'Kutt Maxious', },
        BST = { "Yluc Culmin", 'Paskal Lobb', },
        BER = { "Yluc Culmin", },
        MNK = { "Yluc Culmin", },
        RNG = { "Yluc Culmin", 'LLyndal Desterhoff', },
        ROG = { "Yluc Culmin", },
        MAG = { 'Excellent Raiton Evasion', },
        NEC = { 'Kutt Maxious', },
        WIZ = { 'Excellent Raiton Evasion', },
        BRD = { 'Taky Tabbardt', },
        ENC = { 'Taky Tabbardt', },
        CLR = { 'Maulemas Ragejoy', },
        DRU = { 'LLyndal Desterhoff', },
        SHM = { 'Paskal Lobb', },
    },
    greatdividetwo = {
        WIZ = { 'Aurelia Portrowel', },
        DRU = { 'Aurelia Portrowel', },
    },
    cobaltscartwo = {
        WIZ = { 'Chanter Bjiatel', },
        DRU = { 'Chanter Bjiatel', },
    },
    westwastestwo = {
        WAR = { "Knox Ridordy", "Krykorn Elsonower", },
        PAL = { "Kimbrose Galivan", "Krykorn Elsonower", },
        SHD = { "Kimbrose Galivan", "Krykorn Elsonower", },
        BST = { "Beestibo Saibotaz", "Kimbrose Galivan", "Krykorn Elsonower", },
        BER = { "Knox Ridordy", "Krykorn Elsonower", },
        MNK = { "Knox Ridordy", "Krykorn Elsonower", },
        RNG = { "Kimbrose Galivan", "Krykorn Elsonower", },
        ROG = { "Knox Ridordy", "Krykorn Elsonower", },
        MAG = { 'Beestibo Saibotaz', "Kimbrose Galivan", "Krykorn Elsonower", },
        NEC = { 'Beestibo Saibotaz', "Krykorn Elsonower", },
        WIZ = { 'Beestibo Saibotaz', "Krykorn Elsonower", },
        BRD = { "Kimbrose Galivan", "Krykorn Elsonower", },
        ENC = { 'Beestibo Saibotaz', "Krykorn Elsonower", },
        CLR = { 'Wiltie MacHadden', "Krykorn Elsonower", },
        DRU = { 'Wiltie MacHadden', "Krykorn Elsonower", },
        SHM = { 'Wiltie MacHadden', "Krykorn Elsonower", },
    },
    maidentwo = {
        WAR = { "Tetorau Xi Xundraux", },
        PAL = { "Dabo Xi Xiall", 'Tetorau Xi Xundraux', },
        SHD = { "Dabo Xi Xakreum", 'Tetorau Xi Xundraux', },
        BST = { "Tetorau Xi Tetoracu", 'Tetorau Xi Xundraux', },
        BER = { "Tetorau Xi Xundraux", },
        MNK = { "Tetorau Xi Xundraux", },
        RNG = { "Ishta Xi Ivanieum", 'Tetorau Xi Xundraux', },
        ROG = { "Tetorau Xi Xundraux", },
        MAG = { 'Dabo Xi Atraeth', },
        NEC = { 'Dabo Xi Xakreum', },
        WIZ = { 'Byron Tueleb', 'Dabo Xi Atraeth', },
        BRD = { "Tetorau Xi Tatrau", },
        ENC = { 'Tetorau Xi Tatrau', },
        CLR = { 'Dabo Xi Xiall', },
        DRU = { 'Byron Tueleb', 'Ishta Xi Ivanieum', },
        SHM = { 'Tetorau Xi Tetoracu', },
    },
    sharvahltwo = {
        WAR = { "Scribe Natji", 'Elder Veteran Muhrak', },
        PAL = { "Scribe Dav", 'Scribe Natji', 'Elder Veteran Muhrak', },
        SHD = { "Scribe Shiara", 'Scribe Natji', 'Elder Veteran Muhrak', },
        BST = { "Scribe Gefna", 'Scribe Natji', 'Scribe Kaleej', 'Elder Veteran Muhrak', },
        BER = { "Scribe Natji", 'Elder Veteran Muhrak', },
        MNK = { "Scribe Natji", 'Elder Veteran Muhrak', },
        RNG = { "Scribe Grawl", 'Scribe Natji', 'Elder Veteran Muhrak', },
        ROG = { "Scribe Natji", 'Elder Veteran Muhrak', },
        MAG = { 'Scribe Lar', 'Elder Veteran Muhrak', },
        NEC = { 'Scribe Shiara', 'Elder Veteran Muhrak', },
        WIZ = { 'Byron Tueleb', 'Scribe Lar', 'Elder Veteran Muhrak', },
        BRD = { 'Scribe Qualia', "Scribe Mojir", "Scribe Tolniq", 'Elder Veteran Muhrak', },
        ENC = { 'Scribe Mojir', 'Elder Veteran Muhrak', },
        CLR = { 'Scribe Dav', 'Elder Veteran Muhrak', },
        DRU = { 'Byron Tueleb', 'Scribe Grawl', 'Elder Veteran Muhrak', },
        SHM = { 'Scribe Gefna', 'Scribe Cholsa', 'Elder Veteran Muhrak', },
    },
    laurioninn = {
        WAR = { 'Frost Hardwood', },
        PAL = { 'Faustus Grotter', },
        SHD = { 'Malessence Torte', },
        BST = { 'Grample Spruce', },
        BER = { 'Frost Hardwood', },
        MNK = { 'Frost Hardwood', },
        RNG = { 'Buthor Glades', },
        ROG = { 'Frost Hardwood', },
        MAG = { 'Erasmus Waterford', },
        NEC = { 'Malessence Torte', },
        WIZ = { 'Erasmus Waterford', },
        BRD = { 'Bradword Clang', },
        ENC = { 'Bradword Clang', },
        CLR = { 'Faustus Grotter', },
        DRU = { 'Buthor Glades', },
        SHM = { 'Grample Spruce', },
    },

}

return MerchLookup
